### PR TITLE
Show debug prompt when tail is cancelled (ctrl+c)

### PR DESCRIPTION
**Pull request by edwardrf**

### CODE REVIEW

**Review by nullfunc — COMMENTED** [review]
LGTM

May be change line 894 (term.Debug) to use a term.Errorf so users can see why the aiDebug didn't start up

**Review by lionello — CHANGES_REQUESTED** [review]
@nullfunc 's comment is a good point, just silently failing was fine when we didn't have the y/n prompt, but now we need to show something, warn or error.

More importantly, on ctrl-c the contexts will be canceled and `cli.Debug` will fail immediately.

**Comment by edwardrf** [comment]
>Also not sure how I feel about ctrl-c not aborting the CLI but only aborting part of the command. It might not be what's expected. We could decide to unhide defang debug and show that in a hint after abort.

This is a misunderstanding from our meeting yesterday, I was under the impression this is intended solution for quicker jump to debug when user sees error and wants to stop. If that is not the intended behaviour, i'll remove this behavior.

**Comment by lionello** [comment]
already in main

**Pull request closed without merging**
